MCU = at90usb1286

BOOTLOADER = halfkay

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
BACKLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes

AUDIO_ENABLE = yes

BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm

DIP_SWITCH_ENABLE = yes

ENCODER_ENABLE = yes

HAPTIC_ENABLE = yes
HAPTIC_DRIVER += SOLENOID

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

PS2_MOUSE_ENABLE = yes
PS2_USE_BUSYWAIT = yes
# PS2_USE_INT = yes
# PS2_USE_USART = yes

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = WS2812

RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812
