#pragma once

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
#define TAPPING_TERM_PER_KEY

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

#undef RGBLIGHT_ANIMATIONS
#undef RGBLED_SPLIT
/* #define RGBLED_SPLIT { 1, 1 } */
#undef RGBLED_NUM
#define RGBLED_NUM 2
#define RGBLIGHT_LAYERS
#define RGBLIGHT_SLEEP

#define SPLIT_USB_DETECT
#define SPLIT_MODS_ENABLE
#define SPLIT_TRANSPORT_MIRROR

#define VIM_FOR_MAC
#define BETTER_VISUAL_MODE
#define VIM_G_MOTIONS
#define VIM_PASTE_BEFORE
#define VIM_REPLACE
#define VIM_W_BEGINNING_OF_WORD
