#define SPLIT_MODS_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#undef RGBLIGHT_SPLIT
#define RGBLIGHT_SPLIT {6, 8}
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_DEFAULT_HUE 128
#define RGBLIGHT_LAYERS
#define RGBLIGHT_SLEEP

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
#define TAPPING_TOGGLE 1

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

/* #undef LOCKING_SUPPORT_ENABLE */
/* #undef LOCKING_RESYNC_ENABLE */

#undef CAPS_LOCK_LED_PIN
#define CAPS_LOCK_LED_PIN D4
