/* #define USE_I2C */
/* #define MASTER_RIGHT */
#define SPLIT_USB_DETECT
#define SPLIT_MODS_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define RGBLIGHT_SPLIT

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

#define RGBLIGHT_DEFAULT_HUE 128
#define RGBLIGHT_SLEEP
#undef RGBLIGHT_ANIMATIONS
