#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY
#define TAPPING_TERM_PER_KEY

#define RGBLIGHT_SLEEP
#ifdef LED_CAPS_LOCK_PIN
    #undef LED_CAPS_LOCK_PIN
#endif
