#pragma once

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
#define TAPPING_TERM_PER_KEY

#ifdef MOUSEKEY_ENABLE
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0
#endif

#ifdef PS2_MOUSE_ENABLE
#define PS2_MOUSE_SCROLL_DIVISOR_H 32
#define PS2_MOUSE_SCROLL_DIVISOR_V 32
#define PS2_MOUSE_V_MULTIPLIER 0.5
#endif

#ifdef RGBLIGHT_ENABLE
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_LAYERS
#define RGBLIGHT_SLEEP
#endif

#ifdef RGB_MATRIX_ENABLE
#define RGB_DISABLE_TIMEOUT (10 * 60 * 1000)
#define RGB_WHEN_USB_SUSPENDED true
/* #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CUSTOM_ROYGCB */
#endif

#define VIM_FOR_MAC
#define BETTER_VISUAL_MODE
#define VIM_G_MOTIONS
#define VIM_PASTE_BEFORE
#define VIM_REPLACE
